[package]
edition = "2021"
name = "ecies-program"
version = "0.1.0"

[dependencies]
ecies-lib.workspace = true
openvm = { workspace = true, features = ["std"] }
openvm-algebra-guest.workspace = true
openvm-ecc-guest.workspace = true
openvm-k256.workspace = true
